"""empty message

Revision ID: 8bc4737da10a
Revises: 
Create Date: 2026-01-22 15:28:45.164387

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.orm import Session
import sqlalchemy as sa

from seeds.add_initial_data import add_mockup_data


# revision identifiers, used by Alembic.
revision: str = '8bc4737da10a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('isOrdinary', sa.Boolean(), nullable=False),
    sa.Column('periodicity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('valuation', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propertyId', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['propertyId'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propertyId')
    )
    op.create_table('properties_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conceptId', sa.Integer(), nullable=False),
    sa.Column('propertyId', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conceptId'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['propertyId'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('propertiesConceptsId', sa.Integer(), nullable=False),
    sa.Column('transactionType', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['propertiesConceptsId'], ['properties_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = Session(bind=bind)
    add_mockup_data(session)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('properties_concepts')
    op.drop_table('contracts')
    op.drop_table('properties')
    op.drop_table('concepts')
    # ### end Alembic commands ###
